### PR TITLE
Make the crate useable in no_std environments

### PR DESCRIPTION
**Pull request by nicoonoclaste**
- [x] Remove spurious dependencies on `std`:
  - using `core::` instead;
  - removing spurious uses of `std::Vec` and `nalgebra::DMatrix`.
- [x] Update Cargo dependencies accordingly:
  - `assert_approx_eq` is a `dev-dependency` (only used in tests);
  - `nalgebra`'s `std` feature isn't used anymore.
- [x] Add a `std` feature, gate remaining uses of `Vec` (only in discrete Bayes), make the crate `no_std` otherwise.
- [ ] Make the API for discrete Bayes useable in `no_std` environments (i.e. without `Vec`).

This can be checked with:
- `cargo check --tests && cargo check --tests --no-default-features`;
- `cargo nono check`.

### CODE REVIEW

**Comment by nicoonoclaste** [comment]
I'm currently implementing embedded code in Rust that uses such filters, and I would rather contribute `no_std` patches to `filters.rs` (and perhaps improvements in the future as I use it) than NIH my own crate  ;3

**Comment by MichaelMauderer** [comment]
This project had fallen a bit to the wayside, but I'm happy to review and merge your changes.
Going `no-std` seems very useful and was something that I definitely had in mind as a potential feature for this crate.

One suggestion I have upfront is to add a check for `no-std` compliance in the GitHub actions configuration (which I just added) to ensure it won't be broken again.

**Comment by MichaelMauderer** [comment]
I have also just updated the repo to the (for Rust) more common Apache/MIT dual license. So let me know whether you are still fine contributing your PR under the additional Apache license.

**Review by MichaelMauderer — APPROVED** [review]

**Comment by nicoonoclaste** [comment]
> I have also just updated the repo to the (for Rust) more common Apache/MIT dual license. So let me know whether you are still fine contributing your PR under the additional Apache license.

Entirely fine by me  :)

**Comment by nicoonoclaste** [comment]
> This project had fallen a bit to the wayside, but I'm happy to review and merge your changes.
> Going `no-std` seems very useful and was something that I definitely had in mind as a potential feature for this crate.
\o/

I totally understand letting things fall by the wayside for a while, it's absolutely no problem  :)
 
> One suggestion I have upfront is to add a check for `no-std` compliance in the GitHub actions configuration (which I just added) to ensure it won't be broken again.

Done, and thanks for adding CI  :)

**Comment by MichaelMauderer** [comment]
It might also be possible to use `Vec` from the `alloc` instead of `std`. That would still require an allocator to be present though, so it might need a different feature gate. Would that be useful for your use case?

**Comment by nicoonoclaste** [comment]
Oh, good point, the gate should be on `alloc` and not `std`; I will go change that.

`alloc` is still inconvenient for my usecase, but I also don't need discrete Bayes (just using Kalman filters and some IIRs right know), hence why I didn't think very hard on how to make it available on `no_std`.

**Comment by mariusknaust** [comment]
@MichaelMauderer Do you consider to do a release with this PR merged? I think it's quite a big step to have no_std support.

**Comment by MichaelMauderer** [comment]
Done.

**Pull request merged**
