### PR TITLE
common::roll: Use i64::wrapping_sub rather than Wrapping<i64>

### PR DESCRIPTION
**Pull request by nicoonoclaste**
This is a minor simplification but makes it more readable.

Conflicts with #1.

### CODE REVIEW

**Comment by nicoonoclaste** [comment]
Please merge #1 first, then rebase this, as it is simpler to deal with.

**Comment by MichaelMauderer** [comment]
Just a note: you can update a PR by pushing to the source rbang in your repo (even force pusing works fine).

**Comment by nicoonoclaste** [comment]
> Just a note: you can update a PR by pushing to the source rbang in your repo (even force pusing works fine).

I'm aware, I just didn't want to include the changes from #1 in here (at least not before #1 is merged)  :)

**Comment by MichaelMauderer** [comment]
I did a local rebase and this is now in develop.

**Pull request closed without merging**
